package sbnz.integracija;

import model.Country;

rule "Low IDV index country"
	when
		$c: Country (idvIndex < 0.3, countryDevelopmentLevel == Country.DevelompentLevel.UNKNOWN )
	then
		$c.setCountryDevelopmentLevel(Country.DevelompentLevel.LOW);
		update($c);
end

rule "High IDV index country"
	when
		$c: Country (idvIndex > 0.3, countryDevelopmentLevel == Country.DevelompentLevel.UNKNOWN )
	then
		$c.setCountryDevelopmentLevel(Country.DevelompentLevel.HIGH);
		update($c);
end