package sbnz.integracija;

import sbnz.integracija.example.model.Patient;
import sbnz.integracija.example.model.Country;
import sbnz.integracija.example.util.MyLogger;

global MyLogger myLogger;

rule "Patient has high fever - LOW"
	no-loop true
	when
		$p: Patient(lastFever > 37.3, 
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW, 
					coughOrFeverRisk != Patient.Risk.HIGH)
	then
		$p.setCoughOrFeverRisk(Patient.Risk.HIGH);
		myLogger.log("Patient has high fever - LOW " + $p.getName());
		update($p);
end

rule "Patient has cough - LOW"
	no-loop true
	when
		$p: Patient(cough == true, 
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW, 
					coughOrFeverRisk != Patient.Risk.HIGH)
	then
		$p.setCoughOrFeverRisk(Patient.Risk.HIGH);
		myLogger.log("Patient has cough - LOW " + $p.getName());
		update($p);
end

rule "Patient doesn't have high fever - LOW"
	no-loop true
	when
		$p: Patient(lastFever <= 37.3, 
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW, 
					coughOrFeverRisk != Patient.Risk.HIGH)
	then
		$p.addTreatmentMeasure("- Mali rizik COVID19");
		$p.setCoughOrFeverRisk(Patient.Risk.LOW);
		myLogger.log("Patient doesn't have high fever - LOW " + $p.getName());
		//update($p);
end

rule "Patient doesn't have cough - LOW"
	no-loop true
	when
		$p: Patient(cough == false, 
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW, 
					coughOrFeverRisk != Patient.Risk.HIGH)
	then
		$p.addTreatmentMeasure("- Mali rizik COVID19");
		$p.setCoughOrFeverRisk(Patient.Risk.LOW);
		myLogger.log("Patient doesn't have cough - LOW " + $p.getName());
		//update($p);
end


rule "Patient had contact with positive COVID19 case within last 14 days - LOW"
	no-loop true
	when
		$p: Patient(covidPositiveContact == true,
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
					coughOrFeverRisk == Patient.Risk.HIGH,
					contactRisk != Patient.Risk.HIGH)
	then
		$p.setContactRisk(Patient.Risk.HIGH);
		$p.addTreatmentMeasure("- Slucaj pod istragom- Izolacija");
		myLogger.log("Patient had contact with positive COVID19 case within last 14 days - LOW " + $p.getName());
		update($p);
end

rule "Patient had contact with positive COVID19 case within last 14 days - reevaluation - LOW"
	no-loop true
	when
		$p: Patient($patients: contactedPatients,
					covidPositiveContact == false,
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
					coughOrFeverRisk == Patient.Risk.HIGH,
					contactRisk != Patient.Risk.HIGH)
		$intValue: Integer() from accumulate(
								Patient(
									covidStatus == Patient.CovidStatus.POSITIVE
								) from $patients,
								sum(1)
							)
		eval($intValue > 0)
	then
		$p.setContactRisk(Patient.Risk.HIGH);
		$p.setCovidPositiveContact(true);
		$p.addTreatmentMeasure("- Slucaj pod istragom- Izolacija");
		myLogger.log("Patient had contact with positive COVID19 case within last 14 days - reevaluation - LOW " + $p.getName());
		update($p);
end

rule "Patient visited country that has covid cases - LOW"
	no-loop true
	when
		$p: Patient($countries: countriesVisited,
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
					coughOrFeverRisk == Patient.Risk.HIGH,
					contactRisk != Patient.Risk.HIGH)
		$intValue: Integer() from accumulate(
								Country(
									covidPositive == true
								) from $countries,
								sum(1)
							)
		eval($intValue > 0)
	then
		$p.setContactRisk(Patient.Risk.HIGH);
		$p.addTreatmentMeasure("- Slucaj pod istragom- Izolacija");
		myLogger.log("Patient visited country that has covid cases - LOW " + $p.getName());
		update($p);
end

rule "Patient didn't have contact with positive COVID19 case within last 14 days - LOW"
	no-loop true
	when
		$p: Patient(covidPositiveContact == false,
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
					coughOrFeverRisk == Patient.Risk.HIGH,
					contactRisk != Patient.Risk.HIGH)
	then
		$p.setContactRisk(Patient.Risk.LOW);
		$p.addTreatmentMeasure("- Mali rizik COVID19");
		myLogger.log("Patient didn't have contact with positive COVID19 case within last 14 days - LOW " + $p.getName());
		//update($p);
end

rule "Patient didn't have contact with positive COVID19 case within last 14 days - reevaluation - LOW"
	no-loop true
	when
		$p: Patient($patients: contactedPatients,
					covidPositiveContact == false,
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
					coughOrFeverRisk == Patient.Risk.HIGH,
					contactRisk != Patient.Risk.HIGH)
		$intValue: Integer() from accumulate(
								Patient(
									covidStatus == Patient.CovidStatus.POSITIVE
								) from $patients,
								sum(1)
							)
		eval($intValue > 0)
	then
		$p.setContactRisk(Patient.Risk.LOW);
		$p.addTreatmentMeasure("- Mali rizik COVID19");
		myLogger.log("Patient didn't have contact with positive COVID19 case within last 14 days - reevaluation - LOW " + $p.getName());
		//update($p);
end

rule "Patient didn't visited country that has covid cases - LOW"
	no-loop true
	when
		$p: Patient($countries: countriesVisited,
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
					coughOrFeverRisk == Patient.Risk.HIGH,
					contactRisk != Patient.Risk.HIGH)
		$intValue: Integer() from accumulate(
								Country(
									covidPositive == true
								) from $countries,
								sum(1)
							)
		eval($intValue > 0)
	then
		$p.setContactRisk(Patient.Risk.LOW);
		$p.addTreatmentMeasure("- Mali rizik COVID19");
		myLogger.log("Patient didn't visited country that has covid cases - LOW " + $p.getName());
		//update($p);
end

rule "Patient has Tachypnea - LOW"
	no-loop true
	when
		$p: Patient(respiratoryRate > 20,
		 	country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
		 	coughOrFeverRisk == Patient.Risk.HIGH,
			contactRisk == Patient.Risk.HIGH,
			oxygenRisk != Patient.Risk.HIGH)
	then
		myLogger.log("Patient has Tachypnea - LOW " + $p.getName());
		$p.setOxygenRisk(Patient.Risk.HIGH);
		$p.setTachnypnea(true);
		$p.addTreatmentMeasure("- Suplementacioni kiseonik- Nazofaringealni bris");
		$p.setShouldDoTest(true);
		update($p);
end

rule "Patient does not have Tachypnea - LOW"
	no-loop true
	when
		$p: Patient(respiratoryRate <= 20,
		 	country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
		 	coughOrFeverRisk == Patient.Risk.HIGH,
			contactRisk == Patient.Risk.HIGH,
			oxygenRisk != Patient.Risk.HIGH)
	then
		myLogger.log("Patient does not have Tachypnea - LOW " + $p.getName());
		$p.setOxygenRisk(Patient.Risk.LOW);
		$p.addTreatmentMeasure("- Nazofaringealni bris");
		$p.setShouldDoTest(true);
		update($p);
end

rule "Patient has Hypoxia - LOW"
	no-loop true
	when
		$p: Patient(oxygenSaturation < 93,
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
					coughOrFeverRisk == Patient.Risk.HIGH,
					contactRisk == Patient.Risk.HIGH,
					oxygenRisk != Patient.Risk.HIGH)
	then
		myLogger.log("Patient has Hypoxia - LOW " + $p.getName());
		$p.setHypoxia(true);
		$p.setOxygenRisk(Patient.Risk.HIGH);
		$p.addTreatmentMeasure("- Suplementacioni kiseonik- Nazofaringealni bris");
		$p.setShouldDoTest(true);
		update($p);
end

rule "Patient does not have Hypoxia - LOW"
	no-loop true
	when
		$p: Patient(oxygenSaturation >= 93,
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
					coughOrFeverRisk == Patient.Risk.HIGH,
					contactRisk == Patient.Risk.HIGH,
					oxygenRisk != Patient.Risk.HIGH)
	then
		myLogger.log("Patient does not have Hypoxia - LOW " + $p.getName());
		$p.setOxygenRisk(Patient.Risk.LOW);
		$p.addTreatmentMeasure("- Nazofaringealni bris");
		$p.setShouldDoTest(true);
		update($p);
end

rule "Test is positive - LOW"
	no-loop true
	when
		$p: Patient(shouldDoTest == true,
					testResults == Patient.CovidStatus.POSITIVE,
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
					coughOrFeverRisk == Patient.Risk.HIGH)
	then
		myLogger.log("Test is positive - LOW " + $p.getName());
		$p.setCovidStatus(Patient.CovidStatus.POSITIVE);
		$p.addOutputMeasure("- Prijem u predvidjeno odeljenje za podrzavajucu negu");
		//update($p);
end

rule "Test is negative - LOW"
	no-loop true
	when
		$p: Patient(shouldDoTest == true,
					testResults == Patient.CovidStatus.NEGATIVE,
					country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
					coughOrFeverRisk == Patient.Risk.HIGH,
					contactRisk == Patient.Risk.HIGH)
	then
		myLogger.log("Test is negative - LOW " + $p.getName());
		$p.setCovidStatus(Patient.CovidStatus.NEGATIVE);
		$p.addOutputMeasure("- Razmotriti druge uzroke i ponoviti bris ako simptomi potraju 2 dana");
		//update($p);
end

rule "No other covid positive patient in the last two weeks - LOW"
	no-loop true
    when
        $p1: Patient(covidStatus == Patient.CovidStatus.NEGATIVE,
					 testResults == Patient.CovidStatus.NEGATIVE,
					 country.countryDevelopmentLevel == Country.DevelompentLevel.LOW,
					 $c: country)
		        Number(intValue == 0 ) from accumulate(
        		$p2: Patient(
        			this != $p1,
        			covidStatus == Patient.CovidStatus.POSITIVE,
        			this meets[2m] $p1
        		) from $c.getPatient(),
        		count($p2)
        )
    then
    	$c.setCovidPositive(false);
end